# Generated by Django 4.2.7 on 2025-10-28 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('report_date', models.DateField(verbose_name='报告日期')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='报告人')),
            ],
            options={
                'verbose_name': '日报',
                'verbose_name_plural': '日报',
                'ordering': ['-report_date'],
                'unique_together': {('report_date',)},
            },
        ),
        migrations.CreateModel(
            name='WarehouseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contractor_company', models.CharField(max_length=100, verbose_name='劳务公司')),
                ('attendance_count', models.PositiveIntegerField(verbose_name='今日到岗人数')),
                ('work_type', models.CharField(max_length=50, verbose_name='工种')),
                ('actual_hours', models.PositiveIntegerField(verbose_name='实际工时')),
                ('yesterday_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='昨日成本')),
                ('cost_per_ticket', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='单票成本')),
                ('exception_notes', models.TextField(blank=True, verbose_name='异常说明')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_reports', to='portal.dailyreport', verbose_name='日报')),
            ],
            options={
                'verbose_name': '仓内报告',
                'verbose_name_plural': '仓内报告',
                'ordering': ['contractor_company'],
            },
        ),
        migrations.CreateModel(
            name='SortingMachineReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('machine_name', models.CharField(max_length=50, verbose_name='分拣机名称')),
                ('machine_type', models.CharField(max_length=30, verbose_name='分拣机类型')),
                ('throughput', models.PositiveIntegerField(verbose_name='处理量(件/小时)')),
                ('error_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='错误率(%)')),
                ('downtime_hours', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='停机时间(小时)')),
                ('maintenance_status', models.CharField(max_length=20, verbose_name='维护状态')),
                ('exception_notes', models.TextField(blank=True, verbose_name='异常说明')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorting_machine_reports', to='portal.dailyreport', verbose_name='日报')),
            ],
            options={
                'verbose_name': '分拣机报告',
                'verbose_name_plural': '分拣机报告',
                'ordering': ['machine_name'],
            },
        ),
        migrations.CreateModel(
            name='QualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quality_type', models.CharField(max_length=30, verbose_name='质量类型')),
                ('total_count', models.PositiveIntegerField(verbose_name='总件数')),
                ('error_count', models.PositiveIntegerField(verbose_name='错误件数')),
                ('error_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='错误率(%)')),
                ('improvement_measures', models.TextField(blank=True, verbose_name='改进措施')),
                ('exception_notes', models.TextField(blank=True, verbose_name='异常说明')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_reports', to='portal.dailyreport', verbose_name='日报')),
            ],
            options={
                'verbose_name': '质量报告',
                'verbose_name_plural': '质量报告',
                'ordering': ['quality_type'],
            },
        ),
        migrations.CreateModel(
            name='PickupReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pickup_area', models.CharField(max_length=20, verbose_name='揽收区域')),
                ('pickup_situation', models.TextField(verbose_name='揽收情况')),
                ('return_count', models.PositiveIntegerField(verbose_name='回库件数')),
                ('exception_notes', models.TextField(blank=True, verbose_name='异常说明')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_reports', to='portal.dailyreport', verbose_name='日报')),
            ],
            options={
                'verbose_name': '揽收报告',
                'verbose_name_plural': '揽收报告',
                'ordering': ['pickup_area'],
            },
        ),
        migrations.CreateModel(
            name='LinehaulReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('supplier', models.CharField(max_length=100, verbose_name='干线供应商')),
                ('transport_type', models.CharField(max_length=50, verbose_name='发运类型')),
                ('vehicle_type_count', models.PositiveIntegerField(verbose_name='车型及次数')),
                ('billing_logic', models.CharField(max_length=50, verbose_name='计费逻辑')),
                ('exception_notes', models.TextField(blank=True, verbose_name='异常说明')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linehaul_reports', to='portal.dailyreport', verbose_name='日报')),
            ],
            options={
                'verbose_name': '干线报告',
                'verbose_name_plural': '干线报告',
                'ordering': ['supplier'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('equipment_name', models.CharField(max_length=50, verbose_name='设备名称')),
                ('equipment_type', models.CharField(max_length=30, verbose_name='设备类型')),
                ('status', models.CharField(max_length=20, verbose_name='运行状态')),
                ('utilization_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='利用率(%)')),
                ('maintenance_hours', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='维护时间(小时)')),
                ('exception_notes', models.TextField(blank=True, verbose_name='异常说明')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_reports', to='portal.dailyreport', verbose_name='日报')),
            ],
            options={
                'verbose_name': '设备报告',
                'verbose_name_plural': '设备报告',
                'ordering': ['equipment_name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('file', models.FileField(upload_to='documents/', verbose_name='文件')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('document_type', models.CharField(choices=[('policy', '政策文件'), ('procedure', '流程文件'), ('form', '表单'), ('template', '模板'), ('other', '其他')], default='other', max_length=20, verbose_name='文档类型')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下载次数')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='部门名称')),
                ('description', models.TextField(blank=True, verbose_name='部门描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='部门经理')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('city', models.CharField(max_length=10, verbose_name='配送城市')),
                ('cargo_volume', models.PositiveIntegerField(verbose_name='货量')),
                ('box_count', models.PositiveIntegerField(verbose_name='分箱数')),
                ('open_time', models.TimeField(verbose_name='开放时间')),
                ('site_situation', models.TextField(blank=True, verbose_name='现场情况')),
                ('delivery_rate_day1', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='第1天达成率(%)')),
                ('delivery_rate_day2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='第2天达成率(%)')),
                ('delivery_rate_day3', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='第3天达成率(%)')),
                ('removed_packages', models.PositiveIntegerField(verbose_name='包裹移除数')),
                ('removal_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='移除率(%)')),
                ('exception_notes', models.TextField(blank=True, verbose_name='异常说明')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_reports', to='portal.dailyreport', verbose_name='日报')),
            ],
            options={
                'verbose_name': '配送报告',
                'verbose_name_plural': '配送报告',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='CostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cost_category', models.CharField(max_length=30, verbose_name='成本类别')),
                ('planned_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='计划成本')),
                ('actual_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实际成本')),
                ('variance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='差异')),
                ('variance_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='差异率(%)')),
                ('exception_notes', models.TextField(blank=True, verbose_name='异常说明')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_reports', to='portal.dailyreport', verbose_name='日报')),
            ],
            options={
                'verbose_name': '成本报告',
                'verbose_name_plural': '成本报告',
                'ordering': ['cost_category'],
            },
        ),
        migrations.CreateModel(
            name='ChangeOrderChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('channel_name', models.CharField(max_length=100, verbose_name='换单渠道')),
                ('change_order_count', models.PositiveIntegerField(verbose_name='换单量')),
                ('exception_notes', models.TextField(blank=True, verbose_name='异常说明')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_order_channels', to='portal.dailyreport', verbose_name='日报')),
            ],
            options={
                'verbose_name': '换单渠道',
                'verbose_name_plural': '换单渠道',
                'ordering': ['channel_name'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AirTransportReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('flight_city', models.CharField(max_length=10, verbose_name='飞航城市')),
                ('pickup_date', models.DateField(verbose_name='揽收日')),
                ('cargo_out_time', models.TimeField(verbose_name='货物出仓时间')),
                ('box_count', models.PositiveIntegerField(verbose_name='箱数')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_transport_reports', to='portal.dailyreport', verbose_name='日报')),
            ],
            options={
                'verbose_name': '空运报告',
                'verbose_name_plural': '空运报告',
                'ordering': ['flight_city'],
            },
        ),
    ]
