# Generated by Django 4.2.7 on 2025-10-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousereport',
            name='yesterday_cost',
        ),
        migrations.AddField(
            model_name='warehousereport',
            name='exchange_count',
            field=models.PositiveIntegerField(default=0, verbose_name='换单数量'),
        ),
        migrations.AddField(
            model_name='warehousereport',
            name='hourly_rate',
            field=models.PositiveIntegerField(default=20, verbose_name='每小时工资'),
        ),
        migrations.AddField(
            model_name='warehousereport',
            name='packages_produced',
            field=models.PositiveIntegerField(default=0, verbose_name='产出包裹数'),
        ),
        migrations.AddField(
            model_name='warehousereport',
            name='sorting_count',
            field=models.PositiveIntegerField(default=0, verbose_name='分拣数量'),
        ),
        migrations.AlterField(
            model_name='warehousereport',
            name='cost_per_ticket',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='单票成本'),
        ),
    ]
