# Generated by Django 4.2.7 on 2025-10-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_warehousereport_yesterday_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousereport',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='总成本'),
        ),
        migrations.AddField(
            model_name='warehousereport',
            name='total_exchange_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='总换单数量'),
        ),
        migrations.AddField(
            model_name='warehousereport',
            name='total_sorting_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='总分拣数量'),
        ),
    ]
