# Generated by Django 4.2.7 on 2025-10-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_warehousereport_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousereport',
            name='actual_attendance_count',
            field=models.PositiveIntegerField(default=0, verbose_name='出勤人数'),
        ),
    ]
