# Generated by Django 4.2.7 on 2025-10-29 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_warehousereport_actual_attendance_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeOrderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('exchange_channel', models.CharField(max_length=100, verbose_name='换单渠道')),
                ('exchange_count', models.PositiveIntegerField(verbose_name='换单量')),
                ('exception_notes', models.TextField(blank=True, verbose_name='异常说明')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_order_reports', to='portal.dailyreport', verbose_name='日报')),
            ],
            options={
                'verbose_name': '换单报告',
                'verbose_name_plural': '换单报告',
                'ordering': ['exchange_channel'],
            },
        ),
    ]
