# Generated by Django 4.2.7 on 2025-10-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_exchangeorderreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airtransportreport',
            options={'ordering': ['-report_date', 'flight_city'], 'verbose_name': '空运报告', 'verbose_name_plural': '空运报告'},
        ),
        migrations.AlterModelOptions(
            name='changeorderchannel',
            options={'ordering': ['-report_date', 'channel_name'], 'verbose_name': '换单渠道', 'verbose_name_plural': '换单渠道'},
        ),
        migrations.AlterModelOptions(
            name='costreport',
            options={'ordering': ['-report_date', 'cost_category'], 'verbose_name': '成本报告', 'verbose_name_plural': '成本报告'},
        ),
        migrations.AlterModelOptions(
            name='deliveryreport',
            options={'ordering': ['-report_date', 'city'], 'verbose_name': '配送报告', 'verbose_name_plural': '配送报告'},
        ),
        migrations.AlterModelOptions(
            name='equipmentreport',
            options={'ordering': ['-report_date', 'equipment_name'], 'verbose_name': '设备报告', 'verbose_name_plural': '设备报告'},
        ),
        migrations.AlterModelOptions(
            name='exchangeorderreport',
            options={'ordering': ['-report_date', 'exchange_channel'], 'verbose_name': '换单报告', 'verbose_name_plural': '换单报告'},
        ),
        migrations.AlterModelOptions(
            name='linehaulreport',
            options={'ordering': ['-report_date', 'supplier'], 'verbose_name': '干线报告', 'verbose_name_plural': '干线报告'},
        ),
        migrations.AlterModelOptions(
            name='pickupreport',
            options={'ordering': ['-report_date', 'pickup_area'], 'verbose_name': '揽收报告', 'verbose_name_plural': '揽收报告'},
        ),
        migrations.AlterModelOptions(
            name='qualityreport',
            options={'ordering': ['-report_date', 'quality_type'], 'verbose_name': '质量报告', 'verbose_name_plural': '质量报告'},
        ),
        migrations.AlterModelOptions(
            name='sortingmachinereport',
            options={'ordering': ['-report_date', 'machine_name'], 'verbose_name': '分拣机报告', 'verbose_name_plural': '分拣机报告'},
        ),
        migrations.AlterModelOptions(
            name='warehousereport',
            options={'ordering': ['-report_date', 'contractor_company'], 'verbose_name': '仓内报告', 'verbose_name_plural': '仓内报告'},
        ),
        migrations.AddField(
            model_name='airtransportreport',
            name='report_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='报告日期'),
        ),
        migrations.AddField(
            model_name='changeorderchannel',
            name='report_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='报告日期'),
        ),
        migrations.AddField(
            model_name='costreport',
            name='report_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='报告日期'),
        ),
        migrations.AddField(
            model_name='deliveryreport',
            name='report_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='报告日期'),
        ),
        migrations.AddField(
            model_name='equipmentreport',
            name='report_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='报告日期'),
        ),
        migrations.AddField(
            model_name='exchangeorderreport',
            name='report_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='报告日期'),
        ),
        migrations.AddField(
            model_name='linehaulreport',
            name='report_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='报告日期'),
        ),
        migrations.AddField(
            model_name='pickupreport',
            name='report_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='报告日期'),
        ),
        migrations.AddField(
            model_name='qualityreport',
            name='report_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='报告日期'),
        ),
        migrations.AddField(
            model_name='sortingmachinereport',
            name='report_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='报告日期'),
        ),
        migrations.AddField(
            model_name='warehousereport',
            name='report_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='报告日期'),
        ),
        migrations.AddIndex(
            model_name='airtransportreport',
            index=models.Index(fields=['report_date'], name='portal_airt_report__7eb50a_idx'),
        ),
        migrations.AddIndex(
            model_name='changeorderchannel',
            index=models.Index(fields=['report_date'], name='portal_chan_report__5c8ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='costreport',
            index=models.Index(fields=['report_date'], name='portal_cost_report__44013c_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryreport',
            index=models.Index(fields=['report_date'], name='portal_deli_report__d54e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentreport',
            index=models.Index(fields=['report_date'], name='portal_equi_report__19345f_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangeorderreport',
            index=models.Index(fields=['report_date'], name='portal_exch_report__ecc25c_idx'),
        ),
        migrations.AddIndex(
            model_name='linehaulreport',
            index=models.Index(fields=['report_date'], name='portal_line_report__b09b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='pickupreport',
            index=models.Index(fields=['report_date'], name='portal_pick_report__7d636d_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityreport',
            index=models.Index(fields=['report_date'], name='portal_qual_report__880ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='sortingmachinereport',
            index=models.Index(fields=['report_date'], name='portal_sort_report__22527c_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousereport',
            index=models.Index(fields=['report_date'], name='portal_ware_report__d3b1a2_idx'),
        ),
    ]
